name: image-build

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up and build
        run: |
            docker buildx create --use --driver cloud ${{ secrets.DOCKER_USER }}/cloud-builder1
            docker buildx build --platform linux/arm64,linux/arm/v7 --builder cloud-0xtest-${{ secrets.DOCKER_USER }}-builder1 --tag ${{ secrets.DOCKER_USER }}/cloud-build-test --push .

