name: image-build

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker buildx with cloud support
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "${{ secrets.DOCKER_USER }}/cloud-builder1"
          install: true
      - name: Set up and build
        run: |
            docker buildx use --builder "cloud-$USER/cloud-builder1"
            docker buildx build --platform linux/arm64,linux/arm/v7 --builder "cloud-$USER-cloud-builder1" --tag "$USER/cloud-build-test" --push .
       end:
           USER: ${{ secrets.DOCKER_USER }}

